### ISSUE TITLE
Create a release including the recent bug fixes

### ISSUE THREAD

**Issue by mortenmj** [bitnami-labs/jenkins-plugins-resolver#55]
It would be very nice to have a release that includes the contributions in #51 and #52

**Comment by mortenmj** [comment]
@jotadrilo Any chance you could have a look at this?

**Comment by psalaberria002** [comment]
It would be very nice to have a release with the latest changes indeed. Whenever you get some time :)

**Comment by jotadrilo** [comment]
Done! See https://github.com/bitnami-labs/jenkins-plugins-resolver/releases/tag/202206211711
